export const elements = [
  {
    number: 60,
    urls: [
      'nature/drvece/Evergreen.png',
      'nature/drvece/A_Lumpy_Evergreen.png',
      'nature/drvece/drvo-slomljeno-01.png',
      'nature/drvece/drvo-slomljeno-02.png',
      'nature/drvece/drvo-slomljeno-04.png',
    ],
  },
  {
    number: 8,
    urls: [
      'buildings/kuca-bunker.png',
      'buildings/kuca-01.png',
      'items/balvani-02.png',
      'items/ograda-01.png',
      'items/vrece-s-peskom.png',
      'items/zidic-07.png',
    ],
  },
  {
    number: 4,
    type: 'vozila',
    urls: [
      'armies/partizani/tenkovi/tenk-04.png',
      'armies/partizani/vozila/dzip-01.png',
    ],
  },
  {
    number: 100,
    type: 'partizani',
    urls: [
      'armies/partizani/bolnicari/bolnicarka-02.png',
      'armies/partizani/vojnici/komesar-01.png',
      'armies/partizani/vojnici/komesar-02.png',
      'armies/partizani/vojnici/mp40-05.png',
      'armies/partizani/vojnici/partizan-01.png',
      'armies/partizani/vojnici/partizan-01-sledja.png',
      'armies/partizani/vojnici/partizan-02.png',
      'armies/partizani/vojnici/partizan-03.png',
      'armies/partizani/vojnici/partizan-04.png',
      'armies/partizani/vojnici/partizan-05.png',
      'armies/partizani/vojnici/partizan-07.png',
      'armies/partizani/vojnici/partizan-08.png',
      'armies/partizani/vojnici/partizan-09.png',
      'armies/partizani/vojnici/partizan-10.png',
      'armies/partizani/vojnici/partizan-11.png',
      'armies/partizani/vojnici/partizan-12.png',
      'armies/partizani/vojnici/partizan-13.png',
      'armies/partizani/vojnici/partizan-14.png',
      'armies/partizani/vojnici/partizan-17.png',
      'armies/partizani/vojnici/partizan-18.png',
      'armies/partizani/vojnici/partizan-21.png',
      'armies/partizani/vojnici/partizan-24.png',
      'armies/partizani/vojnici/partizan-25.png',
      'armies/partizani/vojnici/partizan-28.png',
      'armies/partizani/vojnici/partizan-30.png',
      'armies/partizani/vojnici/stoji-02.png',
      'armies/partizani/marshal-tito.png',
      'armies/rusi/vojnici/zene/borkinja-01.png',
      'armies/rusi/vojnici/zene/borkinja-02.png',
      'armies/rusi/vojnici/zene/borkinja-04.png',
      'armies/rusi/vojnici/zene/mitraljeskinja-01.png',
      'armies/rusi/vojnici/bombas-01.png',
      'armies/rusi/vojnici/bombas-04.png',
      'armies/rusi/vojnici/vojnik-08.png',
      'armies/rusi/vojnici/vojnik-13.png',
      'armies/rusi/vojnici/zastavnik-01.png',
      'armies/rusi/vojnici/zastavnik-04.png',
    ],
  },
  {
    number: 20,
    range: { x: 150, y: 5, z: 150 },
    origin: { x: 0, y: 40, z: 0 },
    type: 'avioni',
    urls: [
      'armies/nemci/avioni/avion-03.png',
      'armies/nemci/avioni/fieseler-fi-156-storch-03.png',
      'armies/nemci/avioni/focke-wulf-fw-190.png',
      'armies/nemci/avioni/fw-190f-8.png',
      'armies/nemci/avioni/Fw_190_A4_Hanning.png',
      'armies/nemci/avioni/junkers-ju87b-stuka.png',
      'armies/nemci/avioni/junkers-ju87d-stuka-03.png',
      'armies/nemci/avioni/junkers-ju-52.png',
      'armies/nemci/avioni/Mesersmit-Bf-109e.png',
    ],
  },
  {
    number: 10,
    range: { x: 100, y: 5, z: 100 },
    origin: { x: 0, y: 35, z: 0 },
    type: 'padobranci',
    urls: [
      'armies/nemci/padobranci/padobranac-01.png',
      'armies/nemci/padobranci/padobranac-03.png',
    ],
  },
]
